name: sarha_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.8
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.0.0
  cloud_functions: ^5.1.3

  # UI
  cupertino_icons: ^1.0.8

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.2
  geolocator_android: ^5.0.2
  permission_handler: ^12.0.1
  geocoding: ^3.0.0
  location: ^7.0.0
  vector_math: ^2.1.4
  provider: ^6.1.2 
  
  

  # Sensors
  sensors_plus: ^6.0.1
  vibration: ^2.0.1

  # Camera
  fl_chart: ^0.66.0
  camera: ^0.10.5+9
  video_player: ^2.8.1
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1  

  # Utilities
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  flutter_tts: ^4.2.0
  intl: ^0.19.0
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.1
  http: ^1.1.0 
  device_info_plus: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#A7B5F4"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/videos/road_driving.mp4