name: sarha_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.8
  cloud_firestore: ^5.5.0

  # UI
  cupertino_icons: ^1.0.8

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  location: ^7.0.0

  # Sensors
  sensors_plus: ^6.0.1

  # Camera
  camera: ^0.10.5+9

  # Utilities
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  flutter_tts: ^4.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#A7B5F4"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
